### ISSUE TITLE
Need Discussion Forum for Requests, Ideas, Questions

### ISSUE THREAD

**Issue by xemjeff** [mitsuba-renderer/nanogui#121]
This repo could really benefit from a User forum or discussion group. This might keep non-issue topics out of the Issues list, and would give us all a chance to communicate with each other and share examples, concepts, and help solve problems.

I think github has a Discussions option one (@svenevs) can activate.  If not, I would  be happy to set up a separate Nanogui discussion group (discourse, etc) hosted elsewhere.

(see also the comment in #96)

**Comment by wjakob** [comment]
That's a great idea! I've opened up a discussions thread.
