### ISSUE TITLE
Example 1 - Question Box comes us with Warning Icon

### ISSUE THREAD

**Issue by xemjeff** [mitsuba-renderer/nanogui#123]
This needs a quick fix:

example1.cpp - line 135:

 ` auto dlg = new MessageDialog(this, MessageDialog::Type::Warning, "Title", "This is a question message", "Yes", "No", true);`

to 

` auto dlg = new MessageDialog(this, MessageDialog::Type::Question, "Title", "This is a question message", "Yes", "No", true);`

**Comment by wjakob** [comment]
Thanks, fixed!
