### ISSUE TITLE
demo dosen't support screen touch ?

### ISSUE THREAD

**Issue by iysheng** [mitsuba-renderer/nanogui#128]
The project is pretty cool, and I run the example1 with opengles support under an aarch64 board which run ``Linux M3568 4.19.193``. And I use a touch screen, but the touch event is no respon, the mouse event is ok. I wonder to know whether the touch screen is support in demo?
![](https://s3.bmp.ovh/imgs/2022/08/26/06bd1d88f630e4e3.jpg)

**Comment by wjakob** [comment]
No touch screen support, but a PR adding this would be welcome.
