### ISSUE TITLE
libnanogui.a Linker errors on Linux

### ISSUE THREAD

**Issue by mike168m** [mitsuba-renderer/nanogui#13]
@wjakob @cyclopsian 
When I try building my project with the latest nanogui from this repo. I get the following when I link

usr/bin/ld: deps/nanogui/libnanogui.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/Filt.dir/build.make:254: recipe for target 'Filt' failed
make[2]: *** [Filt] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/Filt.dir/all' failed
make[1]: *** [CMakeFiles/Filt.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I looked at this commit [commit](https://github.com/mitsuba-renderer/nanogui/commit/51fb59a9763bcfcc3b5e644d8662767e1b28d8aa#diff-af3b638bc2a3e6c650974192a53c7291) and noticed you took out

`list(APPEND NANOGUI_EXTRA_LIBS Xxf86vm Xrandr Xinerama Xcursor Xi X11 pthread)`

on linux builds. I put it back on my local repo and it  works.

**Comment by cyclopsian** [comment]
Those should now be included in the dependencies brought in from linking GLFW. Can you try to delete and re-generate the CMake build folder and see if that fixes it? If it doesn't, please post the exact commands that you used to configure and build the project.

**Comment by cyclopsian** [comment]
I just tested and I was able to see some errors happen when turning off NANOGUI_BUILD_SHARED. Let me get that fixed.

**Comment by cyclopsian** [comment]
Please test #14

**Comment by mike168m** [comment]
Thanks, I'll try this over the weekend.

**Comment by mike168m** [comment]
This fix works. Thanks
