### ISSUE TITLE
Offscreen rendering support? 

### ISSUE THREAD

**Issue by ytrock** [mitsuba-renderer/nanogui#29]
Is it possible to add offscreen rendering functionality in nanogui? 
If not, can you please give some advice on how to implement this function. 
Thanks!

**Comment by wjakob** [comment]
The included examples do use off-screen rendering, e.g. in combination with the GLWidget. You'll unfortunately have to figure this out on your own, I don't have enough time to provide personal support.

**Comment by ytrock** [comment]
Really appreciate!
