### ISSUE TITLE
Incorrect Canvas rendering behaviour on Linux

### ISSUE THREAD

**Issue by KonstantinRr** [mitsuba-renderer/nanogui#51]
It seems like the library uses a wrong offset to render the Canvas widget inside a Window.
This happens when compiling example4 that is part of the official source code. The wrong offset
(in comparison to the window) grows with increasing Window coordinates. This works fine on
Windows.

![image](https://user-images.githubusercontent.com/28897400/89095240-4608ea80-d3cc-11ea-949d-a8e14693e63b.png)

Steps to reproduce:
 1. Compile nanogui on Kubuntu 19.10
 2. Run example 4

**Comment by quadrantica** [comment]
I have the same issue on Windows 10 (19041.338), building with VisualStudio2019.

**Comment by quadrantica** [comment]
I think it is solved by [https://github.com/mitsuba-renderer/nanogui/pull/50](url)

**Comment by KonstantinRr** [comment]
Thanks it is fixed now :+1:
