### ISSUE TITLE
Any tips to make a all-included nanogui executable for distribution?

### ISSUE THREAD

**Issue by n3rdx** [mitsuba-renderer/nanogui#63]
I recently discovered Nanogui, the mitsuba-renderer/nanogui edition. (BTW, is there a version number we can use as shorthand)?

Could I ask the developers for some guidance?

I am developing a cross-platform utility application for servers for Win10, Linux (GUI) using MS Visual Studio 2019 and optional other packages through MS vcpkg tool. After some troubles with the porting of nanogui's stock CMAKE files to a new directory, keeping the distribution in a separate location for inclusion into my codebase, **I have a toolchain up and running**. When I generate my local version of example1, through a cross-linked CMake build file, I can generate executables to a local folder. I see it **does require nanogui.dll** to be present in the local folder. A simple test like renaming nanogui.dll to _nanogui.dll breaks execution. IMHO, if I distribute the package, and somehow the nanogui.dll file is not copied by the user into the folder (or deleted after installing for some reason) **the application will break.** horribly.

1. What options are there for nanogui apps not using a external dll file?
2. What options do developers have in testing for the presence of nanogui routines, or, whether graphics environment is available for rendering - so that we can have a text mode (console) UI?
3. What options do developers have for testing the graphics rendering engines capability (of the host environment) so that we don't ask for GUI that exceeds the systems display capability?  We need to assume user/operator may log in several times using different platforms (mobile, desktop - Win10, desktop - X, text consoles / putty, serial terminals. I miss curses programming on Unix terminals ... which require less resources, but then a mouse/keyboard is what most persons want to use. 
4. What options do developers have for determining the screen display parameters so that the drawing canvas can be defined, and what happens -- in general -- if the operator/user has to resize the window? Does the window / display framework inform nanogui on resizing attempts?
5. Any tips for testing at startup whether nanogui/gui support is available? 

Thanks for publishing nanogui.

**Comment by wjakob** [comment]
Why not compile nanogui statically? The stock CMake files supports this. With regards of these extensions you mention, you'll be on your own -- my resources for supporting this project are extremely limited.
