### ISSUE TITLE
Inclusion in vcpkg

### ISSUE THREAD

**Issue by adi-g15** [mitsuba-renderer/nanogui#64]
Currenly the portfile for nanoGUI uses the wjakob/nanogui version, can this repo be included in it, or it is intentionally the previous version there.

<img width="428" alt="nano_gui" src="https://user-images.githubusercontent.com/37269665/101368754-896ceb80-38cd-11eb-9281-cfc7da583845.png">

* This builds fine for me, just asking whether it will be available on vcpkg ?
** I went through some closed issues regarding building, but they were different

**Comment by xarthurx** [comment]
This is managed by the vcpkg team, not here.
I asked before:
https://github.com/microsoft/vcpkg/issues/8761

But it seems they haven't resolved it fully? You can ask again.
