### ISSUE TITLE
suggestion: use superbuild instead of git submodule

### ISSUE THREAD

**Issue by elegracer** [mitsuba-renderer/nanogui#9]
Maybe I don't understand the philosophy behind this project of using git submodule,
but IMO superbuild makes it much easier to version the dependencies than git submodule.

I use superbuild for my fork of the original nanogui like this:

<https://github.com/elegracer/nanogui>
<https://github.com/elegracer/cmake-superbuild-depends>

And I'd like to know why you use git submodule. If you are willing to tell me, it would be pretty much appreciated!

**Comment by ckaminski** [comment]
Not the project author, but in a world with no dependency management, it's a simple way of ensuring the required projects are downloaded and built, and does so without requiring external tools such as vcpkg or superbuild.  All you need is git and cmake, which you would need anyway.

**Comment by elegracer** [comment]
Yeah.
After a period of time, I also realized that it might be the simplest choice to manage dependencies right now.
It just depends on your environment, so just make it comfortable for you.
Thank you for your reply!
