### ISSUE TITLE
NANOGUI_NATIVE_FLAGS_DEFAULT needs to be an option() instead of set()

### ISSUE THREAD

**Issue by RolandHughes** [mitsuba-renderer/nanogui#91]
CMakeLists.txt:87:  set(NANOGUI_NATIVE_FLAGS_DEFAULT "-march=nehalem")

Cannot successfully override this from the cmake command line.

`RUN cd nanogui && mkdir build && cd build && cmake -DNANOGUI_INSTALL=OFF -DNANOGUI_NATIVE_FLAGS_DEFAULT="-march=armv8.5-a" .. && make
`
```
[  1%] Building C object ext/glfw/src/CMakeFiles/glfw_objects.dir/context.c.o
cc1: error: unknown value ‘nehalem’ for ‘-march’
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a native
make[2]: *** [ext/glfw/src/CMakeFiles/glfw_objects.dir/build.make:82: ext/glfw/src/CMakeFiles/glfw_objects.dir/context.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:403: ext/glfw/src/CMakeFiles/glfw_objects.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

```

Will have to use grep to tweak CMakeLists.txt for now. Other than that and the couple of other issues I reported, this will build in a docker container for arm64. At least it looks like it will.

**Comment by wjakob** [comment]
You can override `NANOGUI_NATIVE_FLAGS` option, no? The `_DEFAULT` variable is just the default value for the option.

**Comment by RolandHughes** [comment]
Possibly, I did not try. I'm not that cmake savy. It's only used in a small percentage of my work. I was able to make sed work fine.
I went with the 2 minute solution rather than lots of research. Sorry if that offends.

**Comment by wjakob** [comment]
no problem, but then it is not a NanoGUI issue.
