### ISSUE TITLE
Significant memory leak (~1mb/second) when using the Metal backend

### ISSUE THREAD

**Issue by Tom94** [mitsuba-renderer/nanogui#93]
When using the Metal backend on macOS, drawing the screen leaks memory. ( Causes https://github.com/Tom94/tev/issues/146 )

Reproduction
==========
All the examples exhibit this problem. `example1` and `example4` are best for reproduction due to their consistent 60fps refresh cycle. Observe the memory usage climbing steadily. Minimizing/hiding the window (Cmd+H) can accelerate the leak further.

In `example2` and `example3`, redraws can be made to happen by dragging the widget around, resulting in a leak of similar magnitude.

What I tracked down so far
=====================
- The OpenGL backend is unaffected
- EDR vs. LDR does not make a difference
- The leak disappears when commenting out `Widget::draw(NVGContext*)` and inherited methods, e.g. by making `Screen::draw_widgets()` a no-op. However it's hard to say whether this implicates `nanovg_metal` or is just a symptom.
  - I tried bringing `nanovg_metal` up to date, but the leak persists.

**Comment by wjakob** [comment]
Oh boy, that's nasty. Fortunately all the objective c++ reference counting seems to be OK. Rather, it's the lack of an autorelease pool that became problematic. Fix here, let me know if that addresses the problem. https://github.com/mitsuba-renderer/nanogui/commit/2d875ad0cd480b8eb01f441e2ef113a258f1effe

You may need to call `autorelease_*` manually from `tev` if your render loop doesn't use `draw_all()`

**Comment by Tom94** [comment]
Confirmed fixed. Thanks a bunch for helping us to quickly! :)
