### ISSUE TITLE
Scroll Bar for TextArea

### ISSUE THREAD

**Issue by RolandHughes** [mitsuba-renderer/nanogui#96]
There is no community forum so this is only place to ask this. All I want to do is put a scrollbar on a TextArea object in a regular TabWidget, not a popup or other kind of Window. I tried adapting example1.cpp but that uses a popup window, creates the VScrollPanel with the popup as parent. 

I tried creating just a Widget, setting fixed size, creating the VScrollPanel using the Widget as parent then having TextArea use the VScrollPanel as parent. No matter what, every time have the VScrollPanel be the parent of the TextArea the TextArea mashes down to one line of height with a tiny little splotch to the right that is the scroll bar. There has _got_ to be a way to put a scrollbar on a TextArea. It is just not obvious how one can get that to work.

**Comment by wjakob** [comment]
This library is a helpful foundation for building a custom GUI, but it does not contain every possible widget. What you describe would likely need some custom widget coding (perhaps basing on the image scroller).
