### ISSUE TITLE
Screen::draw_widgets() eats GB of memory in example3 on Apple M1 Max 

### ISSUE THREAD

**Issue by piotrkundu** [mitsuba-renderer/nanogui#98]
Repro steps:
1. Clone the repo (recursivly)
2. "cd nanogui && mkdir build && cd build && cmake -G Xcode .. && open nanogui.xcodeproj"
3. Run example3. Happens on both release and debug builds.

It's somewhere in nanovg or metal code. renderFlush, renderCommandEncoderWithColorTexture and MTLRenderCommandEncoder are possible suspects.

OSX: 12.0.1 (Monteray)
Macbook Pro 16 M1 Max 64GB RAM
 
<img width="1142" alt="Screenshot 2021-12-16 at 02 41 10" src="https://user-images.githubusercontent.com/8414570/146292394-a515af16-3d4c-4f40-bdee-158b7e0368fb.png">

Comment out [screen->draw_widgets();](https://github.com/mitsuba-renderer/nanogui/blob/master/src/example3.cpp#L190) and everything works fine. 

```
        // Draw nanogui
        //screen->draw_setup();
        //screen->clear(); // glClear
        screen->draw_contents();
        //screen->draw_widgets();
        screen->draw_teardown();
```

<img width="769" alt="Screenshot 2021-12-16 at 02 46 25" src="https://user-images.githubusercontent.com/8414570/146292895-1fc012bb-47d8-4a2e-9cc0-b6824e5e0b68.png">

**Comment by wjakob** [comment]
I pushed a fix, could you see if it works now?

**Comment by piotrkundu** [comment]
Yeah, this fixes the problem. I also tried commenting out `void *pool = autorelease_init();` and `void *pool = autorelease_init();` to see if that was the cause and it was. I would suggest replacing all that with draw_all()

```
    while (!glfwWindowShouldClose(window)) {
        // Check if any events have been activated (key pressed, mouse moved etc.) and call corresponding response functions
        glfwPollEvents();
        screen->draw_all();
        glfwSwapBuffers(window);
    }
```
